=== KaietdePablo/DTD_II/DTD_II/panel_vuelos.dtd
<!ELEMENT panel_vuelos (nombre_aeropuerto, fecha, vuelo+)>
<!ELEMENT nombre_aeropuerto (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT vuelo (diario, origen, destino, hora_salida, hora_llegada, es_salida?)>
<!ATTLIST vuelo codigo ID #REQUIRED>
<!ATTLIST vuelo estado (C | E | R) "E">
<!ELEMENT diario (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>
<!ELEMENT es_salida EMPTY>

=== KaietdePablo/DTD_II/DTD_II/ej3.xml
<!-- 
Nombre: Kaiet de Pablo
Curso: ASIR
Fecha: 03/04/2025
Ejercicio: Aeropuerto
-->
<!DOCTYPE panel_vuelos SYSTEM "panel_vuelos.dtd">
<panel_vuelos>
    <nombre_aeropuerto>JFK</nombre_aeropuerto>
    <fecha>20/12/2013</fecha>
    
    <vuelo codigo="V22" estado="R">
        <diario>SI</diario>
        <origen>New York</origen>
        <destino>Chicago</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>11:30</hora_llegada>
        <es_salida/>
    </vuelo>

    <vuelo codigo="V23" estado="C">
        <diario>NO</diario>
        <origen>New York</origen>
        <destino>Miami</destino>
        <hora_salida>10:15</hora_salida>
        <hora_llegada>11:15</hora_llegada>
        <es_salida/>
    </vuelo>
</panel_vuelos>
